### ISSUE TITLE
intelamt provider interface

### ISSUE THREAD

**Issue by joelrebel** [bmc-toolbox/bmclib#302]
@jacobweinstock In a recent commit I broke a intelamt test https://github.com/bmc-toolbox/bmclib/actions/runs/3856309968/jobs/6572367721#step:4:403

To fix this, Im considering extending the [amtProvider interface](https://github.com/bmc-toolbox/bmclib/blob/main/providers/intelamt/intelamt.go#L31) to include a `IsNil()` method.

Then the `Compatible()` method can check if the instance is `IsNil()`, and will enable  a mock instance to be passed in like you have here https://github.com/bmc-toolbox/bmclib/blob/main/providers/intelamt/intelamt.go#L110.

What are your thoughts on this?

**Comment by jacobweinstock** [comment]
Apologies, i ran through this PR too fast. Why is this needed `amtclient, ok := c.client.(*amt.Client)`? Couldn't a direct check of `c.client == nil` be used?

**Comment by joelrebel** [comment]
The nil check fails to match on the nil interface, and so it needs to be type asserted and checked

**Comment by jacobweinstock** [comment]
Hey Joel, sorry for the delayed response. I don't know if i following here. This code snippet below shows that a nil check on a nil interface does indeed work. Maybe I don't understand what you're saying, sorry.

https://goplay.tools/snippet/xQou00yUQfZ

**Comment by chrisdoherty4** [comment]
https://goplay.tools/snippet/xQou00yUQfZ

Interfaces have a pointer to another construct, that construct could also be a pointer. The `i == nil` check only validates the internal interface pointer is not nil. If the internal interface pointer points to another pointer, that is nil, and tries to use it, it could result in a panic dependent on what the data structure is.

**Comment by chrisdoherty4** [comment]
I took a deeper look at the code and I'm curious if we need 2 ways to initialize `intelamt.Conn`: via `New` and via `Open` having constructed the object. I'm guessing `Open` satisfies some interface? Can we drop `Open` as it would remove the need for `.client == nil` checks?

If `Open` is required, the only check that's needed is `.client == nil` return `"connection uninitialized; Open() must be called Conn can be used"`. While my previous comment is true, its only relevant if some external entity can manipulate the `.client` field. This might be where Jacob was coming form with his [previous comment](https://github.com/bmc-toolbox/bmclib/issues/302#issuecomment-1373890038).

In either case, the `intelamt` package doesn't expose `.client` as a field to be modified so _the `intelamt` package is responsible for ensuring its safely initialized before use_. Unit tests will panic if its not, which is fine because they're catching a programmer error which is their job.

**Comment by joelrebel** [comment]
Thanks for the feedback here, @jacobweinstock fix in #303 seems to work and so I'll close this issue.
